.PHONY: clean All

All:
	@echo "----------Building project:[ competitive_programming - Debug ]----------"
	@cd "competitive_programming" && "$(MAKE)" -f  "competitive_programming.mk"
clean:
	@echo "----------Cleaning project:[ competitive_programming - Debug ]----------"
	@cd "competitive_programming" && "$(MAKE)" -f  "competitive_programming.mk" clean
