.PHONY: clean All

All:
	@echo "----------Building project:[ DSA_using_Cplusplus - Debug ]----------"
	@cd "DSA_using_Cplusplus" && "$(MAKE)" -f  "DSA_using_Cplusplus.mk"
clean:
	@echo "----------Cleaning project:[ DSA_using_Cplusplus - Debug ]----------"
	@cd "DSA_using_Cplusplus" && "$(MAKE)" -f  "DSA_using_Cplusplus.mk" clean
